In [1]:
import tensorflow as tf
import numpy as np

In [2]:
from Tools.Voxelizer import MapperIdVoxelizer
pathDB = "C:\workspace2\Datasets\Chalearn\\"
separator = "\\"
attribute = "R4D_10x10_split200_rctc_customRec_presence_withOut"  # "RelativeDraw0_4D_datasetSave70"#"RelativeCBDraw0_datasetSave60_notOneHot" #"RelativeCBDraw0_datasetSave60" #RelativeDraw0_4D_datasetSave60" #CB
pathPreprocessedData = pathDB + "PreprocessedData" + attribute + separator
pathPreprocessedValidData = pathDB + "PreprocessedDataValid" + attribute + separator
pathPreprocessedTestData = pathDB + "PreprocessedDataTest" + attribute + separator
pathPreprocessedLabel = pathDB + "PreprocessedLabel" + attribute + separator
pathLabelOriginal = pathDB + "Label" + separator
pathCuDiSplit = pathDB + "CuDiSplit" + attribute + separator

dbInfoFileName = "db.info"
hyperParamPreproFileName = "hyperparams_preprocess.info"
pathLog = pathDB + "Log" + separator
physical_devices = tf.config.experimental.list_physical_devices('GPU')
# assert len(physical_devices) > 0, "Not enough GPU hardware devices available"

# configAll = tf.config.experimental.set_memory_growth(physical_devices[0], True)
# tf.config.experimental.set_visible_devices([], 'GPU')
# CUDA_VISIBLE_DEVICES=""
# %% md
### Read db infos and hyperparameters

# %%

# database info (device, protocol path, nbClass..) IN PREPROCESSED FOLDER
finfo = open(pathPreprocessedData + dbInfoFileName, "r")
DBinfos = eval("\n".join(finfo.readlines()))
finfo.close()

# hyperparemters linked to the preprocessing : size of voxelization image, thresholds, subsampling...
finfo = open(pathPreprocessedData + hyperParamPreproFileName, "r")
hyperparams = eval("\n".join(finfo.readlines()))
finfo.close()

idVoxelisation = hyperparams["modeVoxelisation"]
dimensionsImage = np.array(list(hyperparams["dimensionImage"]))
thresholdCuDi = hyperparams["thresholdCuDi"]
toleranceMoveThreshold = hyperparams["toleranceMoveThreshold"]
thresholdToleranceDrawing = hyperparams["thresholdToleranceDrawing"]
jointsSelected = hyperparams["jointSelection"]
nbSkeleton = DBinfos["nbSkeleton"]
nbClass = DBinfos["nbClass"]
pathProtocolFolder = pathDB + "Split" + separator
is4D = "4D" in pathPreprocessedData
if nbSkeleton == 1:
    boxSize = MapperIdVoxelizer.map1sq(idVoxelisation, dimensionsImage, toleranceMoveThreshold, thresholdCuDi,
                                       thresholdToleranceDrawing,
                                       jointsSelected).finalSizeBox()
else:
    boxSize = MapperIdVoxelizer.map2sq(idVoxelisation, dimensionsImage, toleranceMoveThreshold, thresholdCuDi,
                                       thresholdToleranceDrawing,
                                       jointsSelected).finalSizeBox()

# Read config file

In [3]:
# database info (device, protocol path, nbClass..)
finfo = open(pathDB+dbInfoFileName, "r")
DBinfos = eval("\n".join(finfo.readlines()))
finfo.close()

In [4]:
datasetTrain = tf.data.experimental.load(pathPreprocessedData)
datasetValid = tf.data.experimental.load(pathPreprocessedValidData)

In [6]:
ds  = list(iter(datasetTrain))

In [16]:
for data in ds:
    seq = data[0]
    compactZ = tf.math.argmax(seq,axis=3)
    print(tf.shape(compactZ))
    print(compactZ)

    break

tf.Tensor([10 10  8], shape=(3,), dtype=int32)
tf.Tensor(
[[[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 2 2]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0